version: "3"
services:
  mongodb:
    image: mongo:5.0.3
    ports:
      - "27017:27017"
  questionnaire:
    build: .
    ports:
      - "8000:8080"
    environment:
      - spring.data.mongodb.host=mongodb
    depends_on:
      - mongodb